### ISSUE TITLE
The node is NOT on the 'mainnet' network

### ISSUE THREAD

**Issue by gperezalba** [Alethio/ethstats-network-server#12]
Hi,
I'm trying to use ethstats in a private network. I use `docker-compose up` to start the server, dashboard and deepstream. Then I use `docker run -d --restart always --net host -v /home/config/:/root/.config/configstore/ alethio/ethstats-cli --register --account-email your@email.com --node-name your_node_name --server-url http://localhost:3000` so that it connects to my node through RPC, extract data and sends to the server. When I do it I get an error from the server: `"Error: - Message sent on topic: loginResponse = payload: {"success": false, "data":[{"nodeName":"relay_node"}], "errors":["The node is NOT on the 'mainnet' network"]} `. 

What do I have to change to the server to accept connection to my private network? Are all steps the correct ones?

Thanks in advance

Guillermo

**Comment by gperezalba** [comment]
Hi,
Update: I use `docker run -d --restart always --net host -v /home/config/:/root/.config/configstore/ alethio/ethstats-cli --register --account-email your@email.com --node-name your_node_name --server-url http://localhost:3000 --client-url http://localhost:8545`. Now the server shows a Message type 'data' topic 'login' in which detects my node and all related info (such as secretKey, coinbase, net, os...). But inmediately after that I get an error: "Node not found". After that "Connection ended", "Client disconnected" and again "New connection from" and the errors...

Any help is appreciated.

Guillermo

**Comment by baxy** [comment]
Hi @gperezalba, 

The first error you get is because you didn't set the correct value for the "NETWORK_ID" env var in the server section of the docker compose file. It should have the value set in the genesis file of your private network.

Now regarding the second error, not sure which docker compose file you used for firing up the server, but I would assume is the one with memory persistence. In this case if you restart the server the already registered nodes are lost. And because the config file for "ethstats-cli" (where the nodeName and secretKey is stored) is persisted in the defined docker volume, you are trying to connect with auth data that the server doesn't know about. So a possible solution is to delete the config file "ethstats-cli.json" inside the defined volume folder and run the docker command again.

Hope it helps.

**Comment by gperezalba** [comment]
Hi @baxy 

Both answers are the right ones. It's working now!

You've made a great job with block-explorer and ethstats guys.

Guillermo
